### ISSUE TITLE
can you make a modest menu edition please

### ISSUE THREAD

**Issue by Kolhax** [Addict0919/Addict-Script#12]
(i am broke)
Dont tell me to go work, i have a job, i just dont really want to pay for menu and i just do car stuff, and i know there is smth to spawn a car meet setup at ls custom, and i need it for

yimmenu or Modest

**Comment by Clone69420** [comment]
> (i am broke) Dont tell me to go work, i have a job, i just dont really want to pay for menu and i just do car stuff, and i know there is smth to spawn a car meet setup at ls custom, and i need it for
> 
> yimmenu or Modest

He made a version for Kiddions, just join the Discord and ask for it
